### ISSUE TITLE
Specifying how `fill_value` is handled (if unspecified)

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-specs#133]
The Zarr v2 spec [leaves undefined `fill_value`s as ambiguous]( https://zarr.readthedocs.io/en/stable/spec/v2.html?highlight=fill_value#chunks ):

> If the “fill_value” field is null then the contents of the chunk are undefined.

However if a user writes to a portion of a chunk with different implementations, each implementation will now potentially have different chunks depending on how they handle the `fill_value`.

This can also cause confusion in other contexts ( for example https://github.com/zarr-developers/zarr-python/pull/966 ).

Also this gets mentioned in James' overview in issue ( https://github.com/zarr-developers/zarr-specs/issues/53 ).

Of course there are some advantages of leaving this unspecified. Namely one can use uninitialized memory to allocate each chunk for writing into, which would be a bit faster. Also this can more easily handle new or complicated types where an appropriate default `fill_value` is not entirely obvious.

That said, given some of the issues above, wonder if we should take a different tack and specify `fill_value` for types in v3. Thoughts? 🙂

**Comment by d-v-b** [comment]
What about defining the default fill value for a datatype to be the instance of that type with a binary representation of all 0s? Are there any types where this would be counter-intuitive or bad somehow?

**Comment by jakirkham** [comment]
What does that mean for `bytes`, `str`, `object`, etc.?

**Comment by d-v-b** [comment]
I don't know, I never work with those types :) But this "all 0s in its binary representation" idea doesn't seem to make any sense for variable-length types, so it's probably a non-starter. Another option would be to just require a `fill_value`. Explicit is better than implicit and all that.

**Comment by jbms** [comment]
I agree --- fill_value should be required.

There are a few meanings you could potentially assign to an unspecified fill_value:

1. Same as specifying zero or other default value for the type, like empty string.
2. Read returns uninitialized memory --- this is a potential security vulnerability because it may leak information like encryption keys, credentials, etc.
3. Reading a missing chunk returns an error.  However this leads to inconsistent behavior for partially-written chunks, since there is no way to indicate that it is partially written.

Since 1 is the only reasonable option I don't see any advantage in allowing an unspecified fill value.

**Comment by dopplershift** [comment]
NetCDF has a default fill value for each of the types, at least for the classic (netCDF3) format. See the end of the grammar in the [file format spec](https://docs.unidata.ucar.edu/netcdf-c/current/file_format_specifications.html). It's unclear what the defaults are for the rest of the types added for the netCDF4 format, so I'll leave that to @WardF .

**Comment by jakirkham** [comment]
Trying to address in PR ( https://github.com/zarr-developers/zarr-specs/pull/145 )

**Comment by joshmoore** [comment]
Just a heads up that there may be some interesting dangling conversations here.
