### ISSUE TITLE
spec v3: expose ability to see data/ and meta content ?

### ISSUE THREAD

**Issue by Carreau** [zarr-developers/zarr-specs#79]
Currently in v2 spec, some store ability like `listdir()` are pretty straightforward as there is a single namespace. 

in v3 though there is meta/ and data/. Some operation in spec v3 return ambiguous results:

```
# v2
>>> ds.listdir('Tair')

['.zarray',
 '.zattrs',
 '0.0.0',
 '0.0.1',
 '0.1.0',
 '0.1.1',
 '0.2.0',
 '0.2.1',
 '0.3.0',
 '0.3.1'
# v3
>>> ds.listdir('Tair')

['.array',
 '0',
 '1',
 '2',
 ...
# note that `/` is the default separator in v3.
```

As a human it's clear were those are, for an implementation you have to understand the meaning of each of those to know whether they are in `meta/` or `data/` which may requires to actually poke at and load the content of `.array` (or .group?).

It also seem like some extensions _may_ add keys.

Do we want to add some functionalities to tell (without an extra round trip) whether keys are under /meta or /data ?

**Comment by alimanfoo** [comment]
Hi @Carreau, I think there is some mixing of layers here.

IMO stores should be completely ignorant of what keys are being used. Stores just accept keys and values, and store them. They shouldn't inspect or understand what's in the keys or values, the keys are just opaque strings and the values are opaque byte sequences. 

Because of that, a store class should be able to be used with either a v2 or a v3 zarr implementation. I.e., stores are just key/value stores, they don't care what they are storing and are ignorant about the zarr protocol which sits at the layer above them. 

I.e., I would expect the following behaviour from the v2 protocol:

```python
>>> store = zarr.DirectoryStore()
>>> root = zarr.open_v2(store)
>>> arr = root.create('foo/bar', shape=(100, 100), chunks=(50, 50), dtype='f4')
>>> arr[:] = 42
>>> store.list()
['.zarray', '.zattrs', 'foo/.zgroup', 'foo/.zattrs', 'foo/bar/.zarray', 'foo/bar/.zattrs', 'foo/bar/0.0', 'foo/bar/0.1', 'foo/bar/1.0', 'foo/bar/1.1'] 
```

...and the following from v3 protocol:

```python
>>> store = zarr.DirectoryStore()
>>> root = zarr.open_v3(store)
>>> arr = root.create('foo/bar', shape=(100, 100), chunks=(50, 50), dtype='f4')
>>> arr[:] = 42
>>> store.list()
['zarr.json', 'meta/root/foo/bar.array', 'data/foo/bar/0.0', 'data/foo/bar/0.1', 'data/foo/bar/1.0', 'data/foo/bar/1.1'] 
```

The advantage of the v3 protocol is that if you want to discover anything about the hierarchy, the zarr implementation can make use of the `list_pre()` and `list_dir` methods if supported. 

E.g., if a user wants to discover all children of the root ('/') group, they might call:


```python
>>> list(root)
['foo']
```

Under the hood, the zarr v3 implementation would achieve that by calling:

```python
>>> store.list_dir('meta/root/')
{'prefixes': ['foo/'], 'items': []}
```

...which would reveal that there is a child implicit group called 'foo'. This is efficient because it avoids listing any of the chunk keys under the 'data/' prefix.

Similarly, if the user wanted to then discover what children are under the 'foo' group:

```python
>>> list(root['foo'])
['bar']
```

...under the hood the zarr v3 implementation would call:

```python
>>> store.list_dir('meta/root/foo/')
{'prefixes': [], 'items': ['bar.array']}
```

...which would reveal that there is a child array called 'bar'.

**Comment by alimanfoo** [comment]
Btw the `listdir()` method currently implemented on store classes in the Zarr python package only returns a flat list of strings, so there is no way for the implementation to differentiate between results which are "contents" (actual keys) and results which are "sub-directories" (prefixes of keys).

In my example above I assumed that stores implement a `list_dir()` method which behaves slightly differently, because it returns a dict that allows the implementation to differentiate between contents (keys) from sub-directories (prefixes).

See also [how S3 supports listing keys hierarchically](https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingKeysHierarchy.html).
